### ISSUE TITLE
Which file should I download for a Magisk Modules install?

### ISSUE THREAD

**Issue by princeliebe** [Magisk-Modules-Repo/MPixel2Launcher_Magisk#4]
I clone and download the `.zip` file and want to install in Magisk Modules.

Unfortunately the Magisk imported it but said **It doesn't a module**.

May I ask which file should I download?

nexus 6P (but i change something like the name to Pixcel 2 XL to get assistant Google Lens)
8.1
rooted

**Comment by skittles9823** [comment]
You don't need to clone and download to get the module. Just download from the magisk repo.

If you do wish to download it this way, you'll need to extract the zip you've downloaded into a folder and rearchive it so its a zip with all the loose files. If it still doesn't flash, then you'll need to sign the zip.
